package com.playergames.plugin;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.fabricmc.api.DedicatedServerModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.server.command.CommandManager;
import net.minecraft.text.Text;

public final class PGPlugin implements DedicatedServerModInitializer {
    public static final String MOD_ID = "playergamesdefaultplugin";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitializeServer() {
        LOGGER.info("Initializing {} v{}", MOD_ID, PGPlugin.class.getPackage().getImplementationVersion());

        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {
            dispatcher.register(CommandManager.literal("playergames")
                    .executes(ctx -> {
                        ctx.getSource().sendFeedback(() -> Text.literal("This server is running mod(s) generated by https://player.games"), false);
                        return 1;
                    }));
        });
    }
}

